config/routes.rb
Rails.application.routes.draw do
  resources :contatos
  root to: 'contatos#index'
  get '/leads', to: 'leads#index', as: :leads
  get '/leads/:contato_id/new', to: 'leads#new', as: :new_lead

end

app/models/contato.rb
class Contato < ActiveRecord::Base

  validates_presence_of :name, :last_name, :email, :phone
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contatos_controller.rb
class ContatosController < ApplicationController
  before_action :set_contato, only: [:show, :edit, :update, :destroy]

  def index
    @contatos = Contato.all.paginate(:page => params[:page], :per_page => 5)
  end

  def show
  end

  def new
    @contato = Contato.new
  end

  def edit
  end

  def create
    @contato = Contato.new(contato_params)

    respond_to do |format|
      if @contato.save
        format.html { redirect_to @contato, notice: 'Contato was successfully created.' }
        format.json { render :show, status: :created, location: @contato }
      else
        format.html { render :new }
        format.json { render json: @contato.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @contato.update(contato_params)
        format.html { redirect_to @contato, notice: 'Contato was successfully updated.' }
        format.json { render :show, status: :ok, location: @contato }
      else
        format.html { render :edit }
        format.json { render json: @contato.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @contato.destroy
    respond_to do |format|
      format.html { redirect_to contatos_url, notice: 'Contato was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_contato
      @contato = Contato.find(params[:id])
    end

    def contato_params
      params.require(:contato).permit(:name, :last_name, :email, :company, :job_title, :phone, :website)
    end
end

app/controllers/leads_controller.rb
class LeadsController < ApplicationController

  def index
    @leads = LeadCreate.list_leads
  end

  def new
    contato = Contato.find(params[:contato_id])
    message = LeadCreate.create(contato)
    redirect_to leads_path, :notice => message
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contatos_helper.rb
module ContatosHelper
end

app/helpers/leads_helper.rb
module LeadsHelper
end

app/views/contatos/_form.html.erb
<%= form_for(@contato) do |f| %>
  <% if @contato.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contato.errors.count, "error") %> prohibited this contato from being saved:</h2>

      <ul>
      <% @contato.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :company %><br>
    <%= f.text_field :company %>
  </div>
  <div class="field">
    <%= f.label :job_title %><br>
    <%= f.text_field :job_title %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :website %><br>
    <%= f.text_field :website %>
  </div>
  <div class="actions">
    <%= f.submit 'Send', :class => 'btn btn-primary btn-lg outline' %>
  </div>
<% end %>

app/views/contatos/edit.html.erb
<h1>Editing Contato</h1>

<%= render 'form' %>

<%= link_to 'Show', @contato, :class => 'btn btn-primary btn-lg outline' %>
<%= link_to 'Back', contatos_path, :class => 'btn btn-primary btn-lg outline' %>

app/views/contatos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Contatos</h1>

<table id="table-board" class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>Company</th>
      <th>Job title</th>
      <th>Phone</th>
      <th>Website</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contatos.each do |contato| %>
      <tr>
        <td><%= contato.name %></td>
        <td><%= contato.last_name %></td>
        <td><%= contato.email %></td>
        <td><%= contato.company %></td>
        <td><%= contato.job_title %></td>
        <td><%= contato.phone %></td>
        <td><%= contato.website %></td>
        <td class='acoes'><%= link_to 'Show', contato, :class => 'btn btn-primary btn-lg outline' %></td>
        <td class='acoes'><%= link_to 'Edit', edit_contato_path(contato), :class => 'btn btn-primary btn-lg outline' %></td>
        <td class='acoes'><%= link_to 'Destroy', contato, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-primary btn-lg outline' %></td>
        <td class='acoes'><%= link_to 'Add Salesforce', new_lead_path(contato), :class => 'btn btn-primary btn-lg outline' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<div class='pager'><%= will_paginate @contatos, renderer: BootstrapPagination::Rails  %></div>

<%= link_to 'New Contato', new_contato_path, :class => 'btn btn-primary btn-lg outline' %>
<%= link_to 'List Salesforce Leads', leads_path, :class => 'btn btn-primary btn-lg outline' %>

app/views/contatos/new.html.erb
<h1>New Contato</h1>

<%= render 'form' %>

<%= link_to 'Back', contatos_path, :class => 'btn btn-primary btn-lg outline' %>

app/views/contatos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @contato.name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @contato.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @contato.email %>
</p>

<p>
  <strong>Company:</strong>
  <%= @contato.company %>
</p>

<p>
  <strong>Job title:</strong>
  <%= @contato.job_title %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @contato.phone %>
</p>

<p>
  <strong>Website:</strong>
  <%= @contato.website %>
</p>

<%= link_to 'Edit', edit_contato_path(@contato), :class => 'btn btn-primary btn-lg outline' %>
<%= link_to 'Back', contatos_path, :class => 'btn btn-primary btn-lg outline' %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!doctype html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>CONTATOS</title>
  <%= stylesheet_link_tag    'application', :media => 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<script type="text/javascript">
    $(document).ready(function(){
        setTimeout(function(){
            $('.alert').remove();
        }, 2500);
    })
</script>
<body>
<nav class="navbar-inner">
  <div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
      <div class="brand">CONTATOS</div>
      <ul class="nav nav-pills">
      </ul>
    </div>
  </div>
  </div>
</nav>
<div id="main" role="main">
  <div class="container">
    <%= render 'layouts/messages' %>
    <br>
    <%= yield %>
  </div> <!--! end of .container -->
</div> <!--! end of #main -->
</body>
</html>

app/views/leads/index.html.erb
<h1>Listing Salesforce Leads</h1>

<table id="table-board" class="table">
  <thead>
  <tr>
    <th>Name</th>
    <th>Last name</th>
    <th>Email</th>
    <th>Company</th>
    <th>Job title</th>
    <th>Phone</th>
    <th>Website</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @leads.each do |lead| %>
      <tr>
        <td><%= lead.FirstName %></td>
        <td><%= lead.LastName %></td>
        <td><%= lead.Email %></td>
        <td><%= lead.Company %></td>
        <td><%= lead.Title %></td>
        <td><%= lead.Phone %></td>
        <td><%= lead.Website %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<%= link_to 'Back', contatos_path, :class => 'btn btn-primary btn-lg outline' %>